### ISSUE TITLE
Allow separation of sequential_cutoff

### ISSUE THREAD

**Issue by pannal** [g2p/bcache-tools#13]
This is a feature request for a very specific use case:
- having a caching device in front of an md-raid on a machine which serves as a low power media server
- the last writes should be cached on the caching device to reduce the non-sleep time of the raid, together with a huge writeback delay of, let's say, 3 hours
- newest media will always be read from the caching device

I could disable sequential_cutoff or set it rediculously high. That would result in every read being cached into the caching device, too, which in this use case is not wanted.

Could you split up the sequential_cutoff setting to sequential_read_cutoff and sequential_write_cutoff?

Thank you in advance

**Comment by g2p** [comment]
I think this was discussed on the linux-bcache mailing list ([archives](http://blog.gmane.org/gmane.linux.kernel.bcache.devel)) at some point.
You could mention your use case over there: http://vger.kernel.org/vger-lists.html#linux-bcache
This github repo is about the userspace tools, I don't work on the kernel at the moment.
