### ISSUE TITLE
Unable to build with latest GCC

### ISSUE THREAD

**Issue by justin8** [g2p/bcache-tools#25]
The latest GCC throws errors about inline crc64. Completely not a C programmer, but the fix on the debian mailing lists appears to be below:

--- a/bcache.c
+++ b/bcache.c
@@ -115,7 +115,7 @@ static const uint64_t crc_table[256] = {
    0x9AFCE626CE85B507ULL
 };

-inline uint64_t crc64(const void *_data, size_t len)
+uint64_t crc64(const void *_data, size_t len)
 {
    uint64_t crc = 0xFFFFFFFFFFFFFFFFULL;
    const unsigned char *data = _data;

**Comment by rolffokkens** [comment]
Seems like a nice fix. Which reminds me about the fact that the issue was raised earlier:
https://github.com/g2p/bcache-tools/pull/24

**Comment by justin8** [comment]
Ah, I tried searching but must've failed my google fu. I'll close this one then since it is a duplicate and you've got the actual code change done already.
