### ISSUE TITLE
OpenSuse initramfs support

### ISSUE THREAD

**Issue by g2p** [g2p/bcache-tools#6]
Someone with more knowledge of OpenSuse tools should port the [initramfs hook](https://github.com/g2p/bcache-tools/blob/master/initcpio/install), which would allow Suse users to boot from a bcache root filesystem.

See `/lib/mkinitrd/scripts`, https://gitorious.org/opensuse/mkinitrd/source/scripts for the main scripts and https://gitorious.org/opensuse/boot_crypto/source/mkinitrd for a third-party example.

**Comment by l-cdc** [comment]
Hi,
I filed two bug reports that include also a patch.

Please see https://bugzilla.novell.com/show_bug.cgi?id=880845
and https://bugzilla.novell.com/show_bug.cgi?id=880846

I am writing this on OpenSUSE 13.1 with / on LVM on bcache :-)

**Comment by g2p** [comment]
I had forgotten to thank you. Thanks!
